"""
Free movies from multiple sources:
1. YouTube embeddable public domain (2 working movies)
2. Plex free streaming links (15+ movies) WITH TMDB IDs for trailers
"""

def get_public_domain_movies():
    """
    Return FREE movies from YouTube (embedded) + Plex (links)
    All movies include TMDB IDs for trailer fetching
    """
    movies = [
        # === YOUTUBE EMBEDDED (Working) ===
        {
            "id": 9000001,
            "tmdb_id": 843,
            "title": "Nosferatu",
            "overview": "The classic 1922 silent vampire film. Count Orlok brings terror to a small German town.",
            "poster_path": "/iYypPT4bhqXfq1b6EnmxvRt6b2Y.jpg",
            "backdrop_path": "/ffQFnAUm2Uu4RU0nijpjPRf9TBT.jpg",
            "media_type": "movie",
            "release_date": "1922-03-04",
            "vote_average": 7.9,
            "runtime": 94,
            "youtube_id": "FC6jFoYm3xs",
            "is_public_domain": True,
            "genre_ids": [27],
            "free_full_movie": True,
            "source": "youtube"
        },
        {
            "id": 9000002,
            "tmdb_id": 14234,
            "title": "Reefer Madness",
            "overview": "Propagandist film warning against marijuana use. 1936 cult classic now viewed as unintentional comedy.",
            "poster_path": "/sMNm2idVSvJx6AhyO2u2q98l44g.jpg",
            "backdrop_path": "/omnJ6k4hyP3MMbIv6d2Vafp01pP.jpg",
            "media_type": "movie",
            "release_date": "1936-04-19",
            "vote_average": 4.4,
            "runtime": 66,
            "youtube_id": "sbjHOBJzhb0",
            "is_public_domain": True,
            "genre_ids": [18],
            "free_full_movie": True,
            "source": "youtube"
        },
        
        # === PLEX FREE STREAMING (Links to Plex) with TMDB IDs ===
        {
            "id": 218,
            "title": "The Terminator",
            "overview": "A cyborg assassin sent from the future to kill Sarah Connor. Classic 1984 sci-fi action.",
            "poster_path": "/qvktm0BHcnmDpul4Hz01GIazWPr.jpg",
            "backdrop_path": "/6yFoLNQgFdVbA8TZMdfgVpszOla.jpg",
            "media_type": "movie",
            "release_date": "1984-10-26",
            "vote_average": 7.7,
            "runtime": 107,
            "plex_url": "https://watch.plex.tv/movie/the-terminator",
            "is_public_domain": False,
            "genre_ids": [28, 878],
            "free_full_movie": True,
            "source": "plex"
        },
        {
            "id": 1366,
            "title": "Rocky",
            "overview": "A small-time boxer gets a shot at the world heavyweight championship. 1976 Best Picture winner.",
            "poster_path": "/cqxg1CihGR5ge0i1wYXr4Rdeppu.jpg",
            "backdrop_path": "/3cqxg1CihGR5ge0i1wYXr4Rdeppu.jpg",
            "media_type": "movie",
            "release_date": "1976-11-21",
            "vote_average": 7.8,
            "runtime": 119,
            "plex_url": "https://watch.plex.tv/movie/rocky",
            "is_public_domain": False,
            "genre_ids": [18],
            "free_full_movie": True,
            "source": "plex"
        },
        {
            "id": 2667,
            "title": "The Blair Witch Project",
            "overview": "Three student filmmakers disappear while investigating local legends. Found footage horror classic.",
            "poster_path": "/9WCkyEZd15QBwpXgd7PVaJXAy4b.jpg",
            "backdrop_path": "/9WCkyEZd15QBwpXgd7PVaJXAy4b.jpg",
            "media_type": "movie",
            "release_date": "1999-07-14",
            "vote_average": 6.3,
            "runtime": 81,
            "plex_url": "https://watch.plex.tv/movie/the-blair-witch-project",
            "is_public_domain": False,
            "genre_ids": [27],
            "free_full_movie": True,
            "source": "plex"
        },
        {
            "id": 176,
            "title": "Saw",
            "overview": "Two strangers wake up in a deadly game orchestrated by a serial killer. Horror thriller from 2004.",
            "poster_path": "/8FdVJVb6bhWxB4n2dX8JnB97OPk.jpg",
            "backdrop_path": "/8FdVJVb6bhWxB4n2dX8JnB97OPk.jpg",
            "media_type": "movie",
            "release_date": "2004-10-01",
            "vote_average": 7.4,
            "runtime": 103,
            "plex_url": "https://watch.plex.tv/movie/saw",
            "is_public_domain": False,
            "genre_ids": [27, 53],
            "free_full_movie": True,
            "source": "plex"
        },
        {
            "id": 948,
            "title": "Halloween",
            "overview": "Michael Myers escapes from a mental hospital and returns to his hometown to kill. 1978 horror classic.",
            "poster_path": "/wijlZ3HaYMvlDTPqJoTCWKFkCPU.jpg",
            "backdrop_path": "/wijlZ3HaYMvlDTPqJoTCWKFkCPU.jpg",
            "media_type": "movie",
            "release_date": "1978-10-25",
            "vote_average": 7.6,
            "runtime": 91,
            "plex_url": "https://watch.plex.tv/movie/halloween",
            "is_public_domain": False,
            "genre_ids": [27],
            "free_full_movie": True,
            "source": "plex"
        },
        {
            "id": 1678,
            "title": "Godzilla",
            "overview": "Nuclear tests awaken a giant prehistoric monster. Classic 1954 Japanese monster movie.",
            "poster_path": "/6B2XcQkH6LdQOg2fZEXy5Qd0wR1.jpg",
            "backdrop_path": "/6B2XcQkH6LdQOg2fZEXy5Qd0wR1.jpg",
            "media_type": "movie",
            "release_date": "1954-11-03",
            "vote_average": 7.6,
            "runtime": 96,
            "plex_url": "https://watch.plex.tv/movie/godzilla-1954",
            "is_public_domain": False,
            "genre_ids": [878, 27],
            "free_full_movie": True,
            "source": "plex"
        },
        {
            "id": 377,
            "title": "A Nightmare on Elm Street",
            "overview": "Teenagers are stalked by a killer in their dreams. Freddy Krueger horror classic from 1984.",
            "poster_path": "/3md49VL9xF4qGmh4rKbhT4i8jXM.jpg",
            "backdrop_path": "/3md49VL9xF4qGmh4rKbhT4i8jXM.jpg",
            "media_type": "movie",
            "release_date": "1984-11-09",
            "vote_average": 7.3,
            "runtime": 91,
            "plex_url": "https://watch.plex.tv/movie/a-nightmare-on-elm-street-1984",
            "is_public_domain": False,
            "genre_ids": [27],
            "free_full_movie": True,
            "source": "plex"
        },
        {
            "id": 30497,
            "title": "The Texas Chain Saw Massacre",
            "overview": "A group of friends encounter a family of cannibals. 1974 horror masterpiece.",
            "poster_path": "/4LxGw4JRZpOxBPLQK8QO0eNT4Ii.jpg",
            "backdrop_path": "/4LxGw4JRZpOxBPLQK8QO0eNT4Ii.jpg",
            "media_type": "movie",
            "release_date": "1974-10-01",
            "vote_average": 7.3,
            "runtime": 83,
            "plex_url": "https://watch.plex.tv/movie/the-texas-chain-saw-massacre-50th-anniversary",
            "is_public_domain": False,
            "genre_ids": [27],
            "free_full_movie": True,
            "source": "plex"
        },
        {
            "id": 500,
            "title": "Reservoir Dogs",
            "overview": "After a heist goes wrong, criminals suspect one of them is a police informant. Tarantino's debut.",
            "poster_path": "/xi8Iu6qyTfyZVDVy60raIOYJJmk.jpg",
            "backdrop_path": "/xi8Iu6qyTfyZVDVy60raIOYJJmk.jpg",
            "media_type": "movie",
            "release_date": "1992-09-02",
            "vote_average": 8.3,
            "runtime": 99,
            "plex_url": "https://watch.plex.tv/movie/reservoir-dogs",
            "is_public_domain": False,
            "genre_ids": [80, 53],
            "free_full_movie": True,
            "source": "plex"
        },
        {
            "id": 141,
            "title": "Donnie Darko",
            "overview": "A troubled teenager receives visions of a man in a rabbit suit. Cult sci-fi thriller from 2001.",
            "poster_path": "/hihMAkx2n8f6FVkFkHwsXhKI2IL.jpg",
            "backdrop_path": "/hihMAkx2n8f6FVkFkHwsXhKI2IL.jpg",
            "media_type": "movie",
            "release_date": "2001-01-19",
            "vote_average": 7.8,
            "runtime": 113,
            "plex_url": "https://watch.plex.tv/movie/donnie-darko",
            "is_public_domain": False,
            "genre_ids": [878, 18, 9648],
            "free_full_movie": True,
            "source": "plex"
        },
        {
            "id": 792,
            "title": "Platoon",
            "overview": "A young recruit experiences the horrors of the Vietnam War. 1986 Best Picture winner.",
            "poster_path": "/m3mmFkPQKvPZq5exmh0bDuXlD9T.jpg",
            "backdrop_path": "/m3mmFkPQKvPZq5exmh0bDuXlD9T.jpg",
            "media_type": "movie",
            "release_date": "1986-12-19",
            "vote_average": 7.7,
            "runtime": 120,
            "plex_url": "https://watch.plex.tv/movie/platoon",
            "is_public_domain": False,
            "genre_ids": [18, 10752],
            "free_full_movie": True,
            "source": "plex"
        },
        {
            "id": 4488,
            "title": "Friday the 13th",
            "overview": "Camp counselors are stalked by a mysterious killer. Slasher classic from 1980.",
            "poster_path": "/HzrPn1gEHWixfMOvOehOTlHROo.jpg",
            "backdrop_path": "/HzrPn1gEHWixfMOvOehOTlHROo.jpg",
            "media_type": "movie",
            "release_date": "1980-05-09",
            "vote_average": 6.4,
            "runtime": 95,
            "plex_url": "https://watch.plex.tv/movie/friday-the-13th-1980",
            "is_public_domain": False,
            "genre_ids": [27],
            "free_full_movie": True,
            "source": "plex"
        },
        {
            "id": 764,
            "title": "The Evil Dead",
            "overview": "Five friends unleash demonic forces in a cabin in the woods. 1981 horror cult classic.",
            "poster_path": "/uYxQ6xhP3WjqPZtxyAOnZQyx7I6.jpg",
            "backdrop_path": "/uYxQ6xhP3WjqPZtxyAOnZQyx7I6.jpg",
            "media_type": "movie",
            "release_date": "1981-10-15",
            "vote_average": 7.3,
            "runtime": 85,
            "plex_url": "https://watch.plex.tv/movie/the-evil-dead-1981",
            "is_public_domain": False,
            "genre_ids": [27],
            "free_full_movie": True,
            "source": "plex"
        },
        {
            "id": 111,
            "title": "Scarface",
            "overview": "A Cuban refugee rises to become a powerful drug lord in Miami. Crime drama from 1983.",
            "poster_path": "/zAf9U14pwlD6vKILtGW7wGSVqS4.jpg",
            "backdrop_path": "/zAf9U14pwlD6vKILtGW7wGSVqS4.jpg",
            "media_type": "movie",
            "release_date": "1983-12-09",
            "vote_average": 8.2,
            "runtime": 170,
            "plex_url": "https://watch.plex.tv/movie/scarface",
            "is_public_domain": False,
            "genre_ids": [80, 18],
            "free_full_movie": True,
            "source": "plex"
        },
        {
            "id": 28,
            "title": "Apocalypse Now",
            "overview": "A captain is sent to assassinate a rogue colonel during the Vietnam War. Epic war film from 1979.",
            "poster_path": "/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg",
            "backdrop_path": "/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg",
            "media_type": "movie",
            "release_date": "1979-08-15",
            "vote_average": 8.3,
            "runtime": 147,
            "plex_url": "https://watch.plex.tv/movie/apocalypse-now",
            "is_public_domain": False,
            "genre_ids": [18, 10752],
            "free_full_movie": True,
            "source": "plex"
        },
        
        # === NEW PUBLIC DOMAIN MOVIES (YouTube) ===
        {
            "id": 10138,
            "tmdb_id": 10138,
            "title": "Night of the Living Dead",
            "overview": "Zombies trap a group of people in a Pennsylvania farmhouse. George Romero's 1968 horror masterpiece that defined the modern zombie genre.",
            "poster_path": "/inNUOa9WZGdyRXzMO6IZjjJeQyp.jpg",
            "backdrop_path": "/3md49VL9xF4qGmh4rKbhT4i8jXM.jpg",
            "media_type": "movie",
            "release_date": "1968-10-01",
            "vote_average": 7.8,
            "runtime": 96,
            "youtube_id": "f7jkZXvaB4g",
            "is_public_domain": True,
            "genre_ids": [27],
            "free_full_movie": True,
            "source": "youtube"
        },
        {
            "id": 16192,
            "tmdb_id": 16192,
            "title": "Charade",
            "overview": "A woman is pursued by several men who want money her murdered husband stole. Audrey Hepburn and Cary Grant star in this 1963 romantic thriller.",
            "poster_path": "/bQRXWEaPKgHHYnbWgkkl1OmuW0x.jpg",
            "backdrop_path": "/2XJJWUfxZnY.jpg",
            "media_type": "movie",
            "release_date": "1963-12-05",
            "vote_average": 7.9,
            "runtime": 113,
            "youtube_id": "yZrIbC5BK-E",
            "is_public_domain": True,
            "genre_ids": [35, 9648, 53],
            "free_full_movie": True,
            "source": "youtube"
        },
        {
            "id": 90788,
            "tmdb_id": 90788,
            "title": "Plan 9 from Outer Space",
            "overview": "Aliens resurrect the dead to stop humans from creating a doomsday weapon. Ed Wood's infamous 1959 sci-fi B-movie, often called 'worst film ever made.'",
            "poster_path": "/aVYuG7THXg7bgkXFjnq3L3Mr4OH.jpg",
            "backdrop_path": "/aVYuG7THXg7bgkXFjnq3L3Mr4OH.jpg",
            "media_type": "movie",
            "release_date": "1959-07-22",
            "vote_average": 4.2,
            "runtime": 79,
            "youtube_id": "9eANybx9u_s",
            "is_public_domain": True,
            "genre_ids": [27, 878],
            "free_full_movie": True,
            "source": "youtube"
        },
        {
            "id": 25382,
            "tmdb_id": 25382,
            "title": "The Little Shop of Horrors",
            "overview": "A florist raises a plant that feeds on human blood. Roger Corman's 1960 horror comedy featuring a young Jack Nicholson.",
            "poster_path": "/7H9rSmJz5amrYmgQEGfxkOe8J6v.jpg",
            "backdrop_path": "/7H9rSmJz5amrYmgQEGfxkOe8J6v.jpg",
            "media_type": "movie",
            "release_date": "1960-09-01",
            "vote_average": 6.2,
            "runtime": 72,
            "youtube_id": "U8H96jTY9F0",
            "is_public_domain": True,
            "genre_ids": [35, 27],
            "free_full_movie": True,
            "source": "youtube"
        },
        {
            "id": 9000003,
            "tmdb_id": 11652,
            "title": "His Girl Friday",
            "overview": "A newspaper editor tries to prevent his ex-wife from remarrying. Classic 1940 screwball comedy with rapid-fire dialogue starring Cary Grant and Rosalind Russell.",
            "poster_path": "/47S7pMxADIgDECLLIbvP5nAL39p.jpg",
            "backdrop_path": "/47S7pMxADIgDECLLIbvP5nAL39p.jpg",
            "media_type": "movie",
            "release_date": "1940-01-11",
            "vote_average": 7.9,
            "runtime": 92,
            "youtube_id": "W4vJnLshE6Y",
            "is_public_domain": True,
            "genre_ids": [35, 10749],
            "free_full_movie": True,
            "source": "youtube"
        },
        {
            "id": 9000004,
            "tmdb_id": 153,
            "title": "Metropolis",
            "overview": "In a futuristic city sharply divided between working and ruling class, the son of the city planner falls for a working-class prophet. Fritz Lang's 1927 German expressionist masterpiece.",
            "poster_path": "/uwT5EPJnFWRIBUphMdvx2LJqLCF.jpg",
            "backdrop_path": "/uwT5EPJnFWRIBUphMdvx2LJqLCF.jpg",
            "media_type": "movie",
            "release_date": "1927-03-13",
            "vote_average": 8.1,
            "runtime": 153,
            "youtube_id": "ZSExNW0EKso",
            "is_public_domain": True,
            "genre_ids": [18, 878],
            "free_full_movie": True,
            "source": "youtube"
        },
        {
            "id": 9000005,
            "tmdb_id": 454,
            "title": "The Cabinet of Dr. Caligari",
            "overview": "A hypnotist uses a somnambulist to commit murders. Landmark 1920 German silent horror film with iconic expressionist sets.",
            "poster_path": "/evRFXe4emp6bNpV4qqmYx8zCPfT.jpg",
            "backdrop_path": "/evRFXe4emp6bNpV4qqmYx8zCPfT.jpg",
            "media_type": "movie",
            "release_date": "1920-02-27",
            "vote_average": 7.9,
            "runtime": 76,
            "youtube_id": "AP3WDQXkJQY",
            "is_public_domain": True,
            "genre_ids": [18, 27, 53],
            "free_full_movie": True,
            "source": "youtube"
        },
        {
            "id": 9000006,
            "tmdb_id": 11528,
            "title": "The Phantom of the Opera",
            "overview": "A disfigured composer haunts the Paris Opera House. Lon Chaney's iconic 1925 silent horror classic.",
            "poster_path": "/pslJEJObSZWFW2xFgSqLERc2OPg.jpg",
            "backdrop_path": "/pslJEJObSZWFW2xFgSqLERc2OPg.jpg",
            "media_type": "movie",
            "release_date": "1925-09-06",
            "vote_average": 7.3,
            "runtime": 93,
            "youtube_id": "6GQ3U_cAgEE",
            "is_public_domain": True,
            "genre_ids": [27],
            "free_full_movie": True,
            "source": "youtube"
        },
        {
            "id": 9000007,
            "tmdb_id": 315,
            "title": "The General",
            "overview": "A Confederate train engineer tries to recapture his stolen locomotive during the Civil War. Buster Keaton's 1926 silent comedy masterpiece with legendary stunts.",
            "poster_path": "/7FdlSM0RXYJLmYGvWqwfxc6QL4j.jpg",
            "backdrop_path": "/7FdlSM0RXYJLmYGvWqwfxc6QL4j.jpg",
            "media_type": "movie",
            "release_date": "1926-12-31",
            "vote_average": 8.1,
            "runtime": 78,
            "youtube_id": "1AGEcHy9Fwg",
            "is_public_domain": True,
            "genre_ids": [35, 28, 36],
            "free_full_movie": True,
            "source": "youtube"
        },
        {
            "id": 9000008,
            "tmdb_id": 2567,
            "title": "Carnival of Souls",
            "overview": "After a car accident, a woman is haunted by visions of ghouls. Eerie 1962 psychological horror that influenced modern horror cinema.",
            "poster_path": "/2XJJWUfxZnY.jpg",
            "backdrop_path": "/2XJJWUfxZnY.jpg",
            "media_type": "movie",
            "release_date": "1962-09-26",
            "vote_average": 7.1,
            "runtime": 78,
            "youtube_id": "rWDz8PJiLpQ",
            "is_public_domain": True,
            "genre_ids": [27, 9648],
            "free_full_movie": True,
            "source": "youtube"
        },
        {
            "id": 9000009,
            "tmdb_id": 11697,
            "title": "The Man Who Knew Too Much",
            "overview": "A couple's vacation turns into a nightmare when their son is kidnapped. Alfred Hitchcock's tense 1934 thriller.",
            "poster_path": "/kqz0Aj3qGZqQQNUvCHK4Zxkgp7H.jpg",
            "backdrop_path": "/kqz0Aj3qGZqQQNUvCHK4Zxkgp7H.jpg",
            "media_type": "movie",
            "release_date": "1934-12-01",
            "vote_average": 7.5,
            "runtime": 75,
            "youtube_id": "VzV6rVQfG6c",
            "is_public_domain": True,
            "genre_ids": [80, 18, 53],
            "free_full_movie": True,
            "source": "youtube"
        },
        {
            "id": 9000010,
            "tmdb_id": 17178,
            "title": "Detour",
            "overview": "A hitchhiker gets entangled with a mysterious woman. Dark 1945 film noir classic shot in six days on a shoestring budget.",
            "poster_path": "/8PfCGDPY6ERN0xFnq9LR7y9Szx4.jpg",
            "backdrop_path": "/8PfCGDPY6ERN0xFnq9LR7y9Szx4.jpg",
            "media_type": "movie",
            "release_date": "1945-11-30",
            "vote_average": 7.3,
            "runtime": 68,
            "youtube_id": "jW5MxqNSiHg",
            "is_public_domain": True,
            "genre_ids": [80, 53],
            "free_full_movie": True,
            "source": "youtube"
        },
        {
            "id": 9000011,
            "tmdb_id": 54830,
            "title": "Dementia 13",
            "overview": "A family gathers at a castle where an ax murderer is on the loose. Francis Ford Coppola's 1963 directorial debut horror film.",
            "poster_path": "/8hEVAu0FHExEwFKhFMPJPNqWNe9.jpg",
            "backdrop_path": "/8hEVAu0FHExEwFKhFMPJPNqWNe9.jpg",
            "media_type": "movie",
            "release_date": "1963-09-25",
            "vote_average": 5.6,
            "runtime": 75,
            "youtube_id": "Hl3VIuLqq6A",
            "is_public_domain": True,
            "genre_ids": [27, 53],
            "free_full_movie": True,
            "source": "youtube"
        },
        {
            "id": 9000012,
            "tmdb_id": 34804,
            "title": "House on Haunted Hill",
            "overview": "An eccentric millionaire offers $10,000 to anyone who can survive a night in a haunted house. Vincent Price stars in this 1959 horror classic.",
            "poster_path": "/c5mRvQSsT3xG9PaiPnLvPkhtPr2.jpg",
            "backdrop_path": "/c5mRvQSsT3xG9PaiPnLvPkhtPr2.jpg",
            "media_type": "movie",
            "release_date": "1959-02-17",
            "vote_average": 6.8,
            "runtime": 75,
            "youtube_id": "eSLaIb4NKcc",
            "is_public_domain": True,
            "genre_ids": [27, 9648],
            "free_full_movie": True,
            "source": "youtube"
        },
        {
            "id": 9000013,
            "tmdb_id": 34804,
            "title": "Attack of the 50 Foot Woman",
            "overview": "After an alien encounter, a woman grows to giant size and seeks revenge on her cheating husband. Campy 1958 sci-fi B-movie cult classic.",
            "poster_path": "/7H9rSmJz5amrYmgQEGfxkOe8J6v.jpg",
            "backdrop_path": "/7H9rSmJz5amrYmgQEGfxkOe8J6v.jpg",
            "media_type": "movie",
            "release_date": "1958-05-10",
            "vote_average": 5.0,
            "runtime": 66,
            "youtube_id": "ZKVX32oEgmM",
            "is_public_domain": True,
            "genre_ids": [878, 27],
            "free_full_movie": True,
            "source": "youtube"
        },
        {
            "id": 9000014,
            "tmdb_id": 11778,
            "title": "It's a Wonderful Life",
            "overview": "An angel shows a suicidal man what life would be like without him. Frank Capra's beloved 1946 Christmas classic starring Jimmy Stewart.",
            "poster_path": "/bSqt9rhDZx1Q7UZ86dBPKdNomp2.jpg",
            "backdrop_path": "/bSqt9rhDZx1Q7UZ86dBPKdNomp2.jpg",
            "media_type": "movie",
            "release_date": "1946-12-20",
            "vote_average": 8.3,
            "runtime": 130,
            "youtube_id": "iLR3gZrU2Xo",
            "is_public_domain": True,
            "genre_ids": [18, 14, 10751],
            "free_full_movie": True,
            "source": "youtube"
        },
        {
            "id": 9000015,
            "tmdb_id": 5925,
            "title": "Battleship Potemkin",
            "overview": "A dramatized account of the 1905 mutiny on the Russian battleship. Sergei Eisenstein's 1925 revolutionary silent masterpiece featuring the iconic Odessa Steps sequence.",
            "poster_path": "/3GBgBZ3y43qLTzNMkI3uyb7SY2o.jpg",
            "backdrop_path": "/3GBgBZ3y43qLTzNMkI3uyb7SY2o.jpg",
            "media_type": "movie",
            "release_date": "1925-12-24",
            "vote_average": 7.9,
            "runtime": 75,
            "youtube_id": "rHmkAGAaQfs",
            "is_public_domain": True,
            "genre_ids": [18, 36, 10752],
            "free_full_movie": True,
            "source": "youtube"
        },
        {
            "id": 9000016,
            "tmdb_id": 242224,
            "title": "The Last Man on Earth",
            "overview": "A plague turns humanity into vampires, leaving one scientist as the sole survivor. Vincent Price stars in this 1964 adaptation of Richard Matheson's novel.",
            "poster_path": "/ajtqZxGmT2h0Ds8rJ7Dn7eZVdWp.jpg",
            "backdrop_path": "/ajtqZxGmT2h0Ds8rJ7Dn7eZVdWp.jpg",
            "media_type": "movie",
            "release_date": "1964-03-08",
            "vote_average": 6.9,
            "runtime": 86,
            "youtube_id": "B1desrCkauA",
            "is_public_domain": True,
            "genre_ids": [27, 878],
            "free_full_movie": True,
            "source": "youtube"
        },
    ]
    
    return movies


def get_public_domain_by_id(content_id):
    """Get specific public domain movie by ID"""
    movies = get_public_domain_movies()
    for movie in movies:
        if str(movie["id"]) == str(content_id):
            return movie
    return None
